[package]
name = "app"
version = "0.1.8" # x-release-please-version
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"
default-run = "app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "gameroute-capture-service"
path = "src/bin/gameroute_capture_service.rs"

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.9.5", features = ["tray-icon"] }
tauri-plugin-log = "2"
tauri-plugin-opener = "2"
tokio = { version = "1", features = ["sync", "time", "macros", "rt-multi-thread", "process", "io-util"] }
chrono = "0.4"
netstat2 = "0.11.2"
futures = "0.3"
reqwest = { version = "0.13.1", features = ["json"] }
thiserror = "2.0"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "migrate"] }
lru = "0.16.3"
sysinfo = "0.38.0"
steamlocate = "2"
tauri-plugin-dialog = "2"
trippy-core = "^0.13.0"
windows-service = "0.7"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Pipes", "Win32_System_Diagnostics_Etw", "Win32_System_Time"] }
interprocess = "2"
etherparse = "0.18"
uuid = { version = "1", features = ["v4"] }
ctrlc = "3.4"
tauri-plugin-notification = "2.3.3"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "s"

[dev-dependencies]
tempfile = "3"
